games:
  - 'with your mind'
  - 'with m00ch'
  - 'with penguinluff'
  - 'Rim World'
  - 'Destiny 2'
  - 'with atomic bombs'
  - 'with dark matter'
  - 'heads up 7up'
  - 'musical chairs'
protected_roles:
  - 'Monsters'
  - 'Muted'
  - 'Titans (Super-Admins)'
  - 'Demigods (Server-Admins)'
  - 'Heroes'
  - 'Bot Commander'
  - 'Rowdy'

